/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  safelist: [
    // Color classes for dynamic event colors
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-500",
    "bg-blue-600",
    "bg-blue-700",
    "bg-blue-800",
    "bg-blue-900",
    "bg-red-50",
    "bg-red-100",
    "bg-red-500",
    "bg-red-600",
    "bg-red-700",
    "bg-red-800",
    "bg-red-900",
    "bg-green-50",
    "bg-green-100",
    "bg-green-500",
    "bg-green-600",
    "bg-green-700",
    "bg-green-800",
    "bg-green-900",
    "bg-yellow-50",
    "bg-yellow-100",
    "bg-yellow-500",
    "bg-yellow-600",
    "bg-yellow-700",
    "bg-yellow-800",
    "bg-yellow-900",
    "bg-purple-50",
    "bg-purple-100",
    "bg-purple-500",
    "bg-purple-600",
    "bg-purple-700",
    "bg-purple-800",
    "bg-purple-900",
    "bg-pink-50",
    "bg-pink-100",
    "bg-pink-500",
    "bg-pink-600",
    "bg-pink-700",
    "bg-pink-800",
    "bg-pink-900",
    "bg-indigo-50",
    "bg-indigo-100",
    "bg-indigo-500",
    "bg-indigo-600",
    "bg-indigo-700",
    "bg-indigo-800",
    "bg-indigo-900",
    "bg-teal-50",
    "bg-teal-100",
    "bg-teal-500",
    "bg-teal-600",
    "bg-teal-700",
    "bg-teal-800",
    "bg-teal-900",
    "bg-amber-50",
    "bg-amber-100",
    "bg-amber-500",
    "bg-amber-600",
    "bg-amber-700",
    "bg-amber-800",
    "bg-amber-900",
    "bg-lime-50",
    "bg-lime-100",
    "bg-lime-500",
    "bg-lime-600",
    "bg-lime-700",
    "bg-lime-800",
    "bg-lime-900",
    // Text colors
    "text-blue-200",
    "text-blue-800",
    "text-blue-900",
    "text-red-200",
    "text-red-800",
    "text-red-900",
    "text-green-200",
    "text-green-800",
    "text-green-900",
    "text-yellow-800",
    "text-yellow-900",
    "text-purple-200",
    "text-purple-800",
    "text-purple-900",
    "text-pink-200",
    "text-pink-800",
    "text-pink-900",
    "text-indigo-200",
    "text-indigo-800",
    "text-indigo-900",
    "text-teal-200",
    "text-teal-800",
    "text-teal-900",
    "text-amber-800",
    "text-amber-900",
    "text-lime-800",
    "text-lime-900",
    // Border colors
    "border-blue-200",
    "border-blue-700",
    "border-blue-800",
    "border-red-200",
    "border-red-700",
    "border-red-800",
    "border-green-200",
    "border-green-700",
    "border-green-800",
    "border-yellow-700",
    "border-yellow-800",
    "border-purple-200",
    "border-purple-700",
    "border-purple-800",
    "border-pink-200",
    "border-pink-700",
    "border-pink-800",
    "border-indigo-200",
    "border-indigo-700",
    "border-indigo-800",
    "border-teal-700",
    "border-teal-800",
    "border-amber-700",
    "border-amber-800",
    "border-lime-700",
    "border-lime-800",
    // Hover states
    "hover:bg-blue-100",
    "hover:bg-blue-700",
    "hover:bg-blue-800",
    "hover:bg-red-100",
    "hover:bg-red-700",
    "hover:bg-red-800",
    "hover:bg-green-100",
    "hover:bg-green-700",
    "hover:bg-green-800",
    "hover:bg-purple-100",
    "hover:bg-purple-700",
    "hover:bg-purple-800",
    "hover:bg-pink-100",
    "hover:bg-pink-700",
    "hover:bg-pink-800",
    "hover:bg-indigo-100",
    "hover:bg-indigo-700",
    "hover:bg-indigo-800",
    "hover:text-blue-700",
    "hover:text-red-700",
    "hover:text-green-700",
    "hover:text-purple-700",
    "hover:text-pink-700",
    "hover:text-indigo-700",
    "hover:border-blue-700",
    "hover:border-red-700",
    "hover:border-green-700",
    "hover:border-purple-700",
    "hover:border-pink-700",
    "hover:border-indigo-700",
    // Dark mode variants
    "dark:bg-blue-900/20",
    "dark:bg-red-900/20",
    "dark:bg-green-900/20",
    "dark:bg-purple-900/20",
    "dark:bg-pink-900/20",
    "dark:bg-indigo-900/20",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
